# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='drawing',
            new_name='photo',
        ),
    ]
